added Task2_5
Kr14va/Nikita_Kravtsov_DotNet_Course_2021 pull request #8
Opened 2021-09-30 17:48 UTC by Kr14va

2021-09-30 17:49 UTC, Kr14va commented
![](https://github.trello.services/images/mini-trello-icon.png) [Задания №2](https://trello.com/c/0fjOdxti/94-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%E2%84%962)

2021-10-01 14:45 UTC, PaShkadun requested changes

2021-10-01 14:45 UTC, PaShkadun commented on Task2_5/Task5/Program.cs
> +
No whiteline.

2021-10-01 14:45 UTC, PaShkadun commented on Task2_5/Task5/Program.cs
> +            int sideAB = Convert.ToInt32(Console.ReadLine());
Without exception.
Without two upper chars.

2021-10-01 14:45 UTC, PaShkadun commented on Task2_5/Task5/Program.cs
> +
No whiteline.

2021-10-01 14:45 UTC, PaShkadun commented on Task2_5/Task5/Program.cs
> +                if (sideAB == sideBC && sideBC == sideAC && sideAC == sideAB)
Whiteline.

2021-10-01 14:45 UTC, PaShkadun commented on Task2_5/Task5/Program.cs
> +
No whiteline.

2021-10-01 14:45 UTC, PaShkadun commented on Task2_5/Task5/Program.cs
> +                Console.ReadKey();
wtf?

2021-10-03 17:46 UTC, closed without merging